# gcglue project configuration

[app]
name = "Super Mario Strikers"
namespace = "super_mario_strikers"

[input]
path = "assets/super-mario-strikers.nkit.iso"
format = "auto"

[codegen]
output_dir = "generated"
embed_image = true
discover_functions = true
strict_alignment = true

[runtime]
mem1_size = 25165824
aram_size = 67108864
headless = true
memory_card_slot_a = true
gx_fifo_capture_limit = 33554432
gx_latest_frame_stride = 4
